services:
  authentication:
    image: openjdk:21-jdk-slim
    container_name: auth
    working_dir: /auth_app
    volumes:
      - .:/auth_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    command: ["sh", "-c", "./mvnw spring-boot:run"]
    depends_on:
      - mysql

  mysql:
    image: mysql:9.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local